### ISSUE TITLE
Investigate moving to stable

### ISSUE THREAD

**Issue by ccheek21** [ccheek21/fe#1]
When the project started, Rust 2018 was nightly only. Now, there shouldn't be any nightly-only features and the project should probably be switched over to stable.

**Comment by zethra** [comment]
I made two PRs to remove the two feature flags being used.  If merged fe should be able to move to stable once Rust 2018 is released.

https://github.com/ccheek21/fe/pull/2
https://github.com/ccheek21/fe/pull/3

**Comment by wezm** [comment]
Rust 2018 was released this week: https://blog.rust-lang.org/2018/12/06/Rust-1.31-and-rust-2018.html

**Comment by zethra** [comment]
Oh. Yay!

**Comment by ccheek21** [comment]
@zethra After merging your PRs and fixing some tests, it appears to be running and passing all tests on stable! Thanks for the help :)
