### ISSUE TITLE
There's already a crate named FE

### ISSUE THREAD

**Issue by bbatha** [ccheek21/fe#5]
This crate cannot be `cargo install`ed because it conflicts with an [existing crate.](https://crates.io/crates/fe)

**Comment by ccheek21** [comment]
Yeah... I should have done my research first. A rename will be necessary. Any suggestions?

**Comment by ccheek21** [comment]
Currently thinking `fret` for "FREcency Tracking`. Leaving this open for a little while in case anyone else has better suggestions.

**Comment by mwgkgk** [comment]
[fr](https://crates.io/search?q=fr) seems free, also `fre`, `frq`, `freq`, `fq`, `ftr`. I like `fre` and `fr` (and `fe`), not a big fan of `fret`, as i think the pun does not outweigh a somewhat negative meaning. Felt like leaving a comment :) Greatly enjoy the project and use it basically everywhere (files / commands work just as well as directories, except probably for deleting-unexisting). Shame it has to be renamed.

If you feel the pun is > everything I can respect that :+1:

**Comment by ccheek21** [comment]
Funny--I was thinking like "guitar fret" and completely missed the double meaning. I like `fre`, and I'd agree that it seems like a better choice than the somewhat misleading `fret`. I think I'll go ahead and use that so we can get it published. Thanks for the input, and I'm glad you're finding it useful :) 

I'd love to see your implementations for files / commands if you get the chance. I had hacked it together for files (vim only) at one point, but my vimscript abilities are questionable to say the least.

**Comment by ccheek21** [comment]
As an update, I've uploaded the project to `crates.io` under the name `fre`

**Comment by mwgkgk** [comment]
@ccheek21 yet to use it from vim! Hacking custom fzf commands is indeed intimidating. Currently using it for a number of keybinds in `fish`, - things like `M-w` to fzf-cd from current dir. The day will come however.
